export const ALL_TEXT = {
  ADDRESSKEY: "AIzaSyDVIN3eonG7yBS2wqv3S6hEBGe3gcrt0AM",
  AGENTS: "Agents",
  SOMETHING_ERROR: `Something Went Wrong!`,
  DASHBOARD: "Dashboard",
  ALL_PRODUCTS: "ALL_PRODUCTS",
  SINGLE_PRODUCT_DETAILS: "Single Product Details",
  ALL_ORDERS: "All Orders",
  INVOICES: "Invoices",
  USERS: "Users",
  CLAIMS: "Claims",
  SEARCH: "Search",
  CUSTOMERS: "Customers",
  REGISTRATION: "Registrations",
  REGISTER_USER: "Register User",
  VIEW_PROFILE: "View Profile",
  DEACTIVATE: "Deactivate",
  ADD_POLICY: "Add policy",
  CHANGE_PASSWORD: "Change Password",
  ALL: "All",
  CLOSED_CLAIMS: "Closed Claims",
  ERROR_PAGE_DESCRIPTION:
    "The page you are looking for is temporarily unavailable.",
  LOGIN: "Login",
  SEND: "SEND",
  SAVE: "Save",
  ICON: "Icon",
  CHAT: "Chat",
  FORGOT_PASSWORD: "Forgot Password?",
  FORGOT_PASSWORD1: "Forgot Password",
  RESET_PASSWORD: "Reset Password?",
  ENTER_EMAIL: "Enter Email",
  ENTER_PASSWORD: "Enter Password",
  CONFIRM_NEW_PASSWORD: "Confirm New Password",
  WIZARD_STEP_1: "Purchase Policy",
  WIZARD_STEP_2: "Select Payment Method",
  WIZARD_STEP_3: "Review & Pay ",
  SELECT_CARRIER: "Select Carrier",
  SELECT_MAKER: "Select Maker",
  SELECT_MODEL: "Select Model",
  SELECT_YEAR: "Enter Year",
  OTHER_CARRIER: "Other Carrier",
  SELECT_DEDUCTIBLES: "Select Deductibles",
  OTHER_DEDUCTIBLES: "Other Deductibles",
  NOT_AVAILABLE_ID: -1,

  ERROR_PLACEHOLDERS: {
    EMAIL: "Please enter your email address",
    PASSWORD: "Please enter your password",
    CONFIRM_PASSWORD: "Confirm password is required",
    PASSWORD_MUST_BE: "Password must be at least 6 characters",
    NEW_PASSWORD: "Please enter new password",
    NEW_PASSWORD_MATCH_ERROR: `New and confirm passwords must match`,
    INVALID_EMAIL: "Please enter the valid email address",
    PASSWORD_MATCH: "Password must be matched",
    FIRST_NAME: "Please enter your first name",
    LAST_NAME: "Please enter your last name",
    DOB: "Please select your date of birth",
    PHONE: "Please enter your phone number",
    ADDRESS: "Please enter your address",
    CITY: "Please enter your city",
    STATE: "Please enter your state",
    ZIP: "Please select your zip code",
    PLEASE_SELECT: "Please select",
    PLEASE_ENTER: "Please enter",
    CARRIER: "carrier",
    MAKER: "maker",
    MODEL: "model",
    OTHER_DEDUCTIBLES: "Other Deductibles",
    OTHER_CARRIER: "Other Carrier",
    MINIMUM_DEDUCTIBLES: "Minimun deductible should be $100",
    INVALID_DEDUCTIBLES: "Other deductibles must contain valid amount",
    YEAR: {
      number: "Year must be a number",
      integer: "Year must be an integer",
      max: "Year must be less than or equal to 2023",
      min: "Year must be greater than or equal to 1900",
      required: "Year is required",
    },
    DEDUCTIBLES: "deductibles",
  },
  GENERIC_MODAL: {
    SUCCESS: "Success",
    ERROR: "Error",
    ALERT: "Alert",
  },
  USER_DETAIL: {
    ADD_NEW_USER_TITLE: "Add New User",
    FIRST_NAME: "First Name*",
    LAST_NAME: "Last Name*",
    PHONE: "Phone*",
    EMAIL: "Email*",
    ADDRESS: "Address*",
    STATE: "State*",
    CITY: "City*",
    ZIP: "Zip*",
    PASSWORD: "Password",
    CONFIRM_PASSWORD: "Confirm Password",
  },
  FIELD_TYPE_ENUMS: {
    STREET_NUMBER: `street_number`,
    ROUTE: `route`,
    NAIBHOUR: `neighborhood`,
    LOCALITY: `locality`,
    ADMIN: `administrative_area_level_1`,
    CODE: `postal_code`,
  },
  FIELD_VALUE: {
    ADDRESS: "address",
    CITY: "city",
    STATE: "state",
    ZIP: "zip",
  },
};

export const ENUMS = {
  POLICY_TYPES: {
    VEHICLE: {
      VALUE: 0,
      LABEL: "Vehicle",
    },
    DEVICE: {
      VALUE: 1,
      LABEL: "Devices",
    },
    HOME: {
      VALUE: 2,
      LABEL: "Home",
    },
    COMMERCIAL: {
      VALUE: 3,
      LABEL: "Commercial",
    },
  },
  INVOICES: {
    STATUS: {
      SUCCESS: {
        VALUE: 1,
        LABEL: "Success",
      },
      FAILED: {
        VALUE: 0,
        LABEL: "Failed",
      },
    },
  },

  USERS: {
    ROLE: {
      REGISTERED: {
        VALUE: 0,
        LABEL: "Registered",
      },
      CUSTOMER: {
        VALUE: 1,
        LABEL: "Customer",
      },
    },
    STATUS: {
      ACTIVE: {
        VALUE: 1,
        LABEL: "Accept",
      },
      BLACKLISTED: {
        VALUE: 0,
        LABEL: "Reject",
      },
    },
  },
  MODAL_TYPES: {
    SUCCESS: 1,
    ERROR: 2,
    ALERT: 3,
  },
};
