export const images = {
  noDukLogo: "images/logo.jpeg",
  mainLogo: "images/logo.png",
  errorIcon: "images/error-icon.png",
  userIcon: "images/user-dp.jpeg",
  noDukAmdinBackground: "images/nodukAdminBG.svg",
  userLogin: "images/userLogin.svg",
  forgotPassword: "images/forgotPassword.svg",
  resetPassword: "images/resetPassword.svg",
  eyeOpen: "images/eye-open.svg",
  eyeClose: "images/eye-close.svg",
  success: "images/successModal.svg",
  error: "images/errorModal.svg",
  alert: "images/alertModal.svg",
  noImage: "images/no-image.jpeg",
  lockIcon: "images/lockIcon.svg",
};
